In [1]:
import numpy as np

In [13]:
# create a vector
x = np.array([1,2,3,4])

# create a (3*2) matrix

A = np.array([[1,2],[3,4],[5,6]])

# transpose matrix
A_t = A.T


array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# Matrix + Matrix
B = np.array([[1,1],[1,1],[1,1]])
C = A + B
C

array([[2, 3],
       [4, 5],
       [6, 7]])

In [16]:
# matrix add scaler

D = A + 2
D

array([[3, 4],
       [5, 6],
       [7, 8]])

In [17]:
# numpy broadcasting mechanism
# numpy will extend the smaller shape arry to match the shape of the bigger one

# E.shape = (3*1)
E = np.array([[2],[4],[6]])
#broadcasting will extend E.shap = (3*2),its value will be([2,2],[4,4],[6,6])
F = A + E
F

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])