In [1]:
import numpy as np

In [3]:
# matrix dot product
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
B = np.array([[2],[4],[5]])
B

array([[2],
       [4]])

In [5]:
# A.shape = (3*2),B.shape = (2*1) C.shape = (3*1)
# dot product need two matrix shape (m*n) (n*x) ,the dot result will be (m*x) 

C = np.dot(A,B)
C

array([[10],
       [22],
       [34]])

In [ ]:
# matrices mutliplication is distributive and associative ,not commutative



In [20]:
# vector multiplication is commutative

x = np.array([2,6])
x.shape
#y = np.array([[2],[2]])
#z = x.T.dot(y)
#z

(2,)