In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
array = np.eye(3,dtype=int)
print(array)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [9]:
x = np.array([[1],[2],[3]])
print(x)
xid = np.eye(x.shape[0],dtype=int).dot(x)
print(xid)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [3]:
A = np.array([[3,0,2],[2,0,-2],[0,1,1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [4]:
# 反转A矩阵
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [5]:
A_bis = A_inv.dot(A)
A_bis

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [6]:
# 解如下方程组
# y = 2x
# y = -x +3 
# 等价于 2x - y  =0; 
#        x + y = 3
# 解为 x = 1, y = 2.
# A.dot(x) = b 等价于 x = A_inv.dot(b)

A = np.array([[2,-1],[1,1]])
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.33333333,  0.33333333],
       [-0.33333333,  0.66666667]])

In [8]:
b = np.array([[0],[3]]);
x = A_inv.dot(b)
x

array([[1.],
       [2.]])