In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
array = np.eye(3,dtype=int)
print(array)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [9]:
x = np.array([[1],[2],[3]])
print(x)
xid = np.eye(x.shape[0],dtype=int).dot(x)
print(xid)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


NameError: name 'x' is not defined