In [2]:
import numpy as np

In [3]:
u = np.array([1,6])
u

array([1, 6])

In [4]:
v = np.array([4,2])
v

array([4, 2])

In [5]:
u+v

array([5, 8])

In [6]:
np.linalg.norm(u+v)

9.433981132056603

In [8]:
u_norm = np.linalg.norm(u)
v_norm = np.linalg.norm(v)
print(u_norm)
print(v_norm)
u_norm + v_norm

6.082762530298219
4.47213595499958
