In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
A = np.array([[np.cos(50),-np.sin(50)],[np.sin(50),np.cos(50)]])
print(A)

[[ 0.96496603  0.26237485]
 [-0.26237485  0.96496603]]


In [8]:
col0 = A[:,[0]]
col1 = A[:,[1]]
print(col0)
print(col1)

[[ 0.96496603]
 [-0.26237485]]
[[0.26237485]
 [0.96496603]]


In [15]:
row0 = A[0].reshape(A.shape[1],1)
row1 = A[1].reshape(A.shape[1],1)
print(A[0])
print(row0)

[0.96496603 0.26237485]
[[0.96496603]
 [0.26237485]]


In [11]:
col0.T.dot(col1)

array([[0.]])

In [16]:
row0.T.dot(row1)

array([[0.]])

In [17]:
row1.T.dot(row0)

array([[0.]])

In [18]:
A.T.dot(A)

array([[1., 0.],
       [0., 1.]])

In [19]:
A.T

array([[ 0.96496603, -0.26237485],
       [ 0.26237485,  0.96496603]])

In [21]:
np.linalg.inv(A)

array([[ 0.96496603, -0.26237485],
       [ 0.26237485,  0.96496603]])